### PR TITLE
(application: dashboard, notifier) First implementation of Blink Eye Dashboard

### PR DESCRIPTION
**Pull request by Sayad-Uddin-Tahsin**
- ## Overall Changes
  * Added Blink Eye Dashboard
  * Reformatted `blink-eye.py`
  * Added configuration file (`data.json`) on `/application/data/`
  * Changed module for notification (`plyer` -> `winotify`)
  * Added `winotify==1.1.0` instead of `plyer==2.1.0` on `application/REQUIREMENTS.txt`

- ## Dashboard Changes
  * Customizable Screen Break Interval (`SBI`)
  * Customizable Focus Break (`FB`)
  * Save button to update the changes and restart the Notifier

- ## Build Script Changes
  * Modified `pyinstaller` command on `build_fedora.sh` and `build_windows.bat` to add the new Data Folder with the `data.json`
  * Modified Changelog on `application/BlinkEye_Fedora.spec` 
  * Added `data` file on `application/BuildFileForInnoSetup.iss`

### CODE REVIEW

**Comment by Sayad-Uddin-Tahsin** [comment]
On commit [a88cbf1](https://github.com/nomandhoni-cs/blink-eye/pull/40/commits/a88cbf1d0d1528b0b4209e3cb3685875d837a115), the lines that includes `data` & `Assets` folder along with its content is removed as on commit [795806f](https://github.com/nomandhoni-cs/blink-eye/pull/40/commits/795806fbeb334454e758cfdc6007d98e162a185d) the application was made Standalone which means it has now the folders needed included properly.

**Review by nomandhoni-cs — COMMENTED** [review]
This Comment was for https://github.com/nomandhoni-cs/blink-eye/pull/40/commits/57368f93bb5424b833af67db49091579f74205e1 this commit

@Sayad-Uddin-Tahsin, Have you tried to build the App?
I tried and found a permission related error when launching the app, and the dashboard wasn't opening.

#### Here is a possible fix

### Error
image

### Possible Fix
Little change in the innoSetupFile

``` [Files]
Source: "dist\BlinkEye.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\Assets\*"; DestDir: "{app}\Assets\"; Flags: ignoreversion
Source: ".\data\*"; DestDir: "{app}\data\"; Flags: ignoreversion recursesubdirs createallsubdirs

[Dirs]
Name: "{app}\data"; Permissions: users-full
```

## Just a small request: 
#### Additionally, include comments in the code to explain the functionality of each part
#### Please use meaningful variable names.
#### Length is not an issue. Code Readability is more important for project

**Comment by Sayad-Uddin-Tahsin** [comment]
> Please use meaningful variable names.

@nomandhoni-cs, sorry about that I guess I used meaningful names already but obviously it may be felt wrong on your perspective. Can you name the variables you didn't understand or need me to change?

**Comment by nomandhoni-cs** [comment]
> > Please use meaningful variable names.
> 
> @nomandhoni-cs, sorry about that I guess I used meaningful names already but obviously it may be felt wrong on your perspective. Can you name the variables you didn't understand or need me to change?

Almost fine, not a major issue, This was just a request to use meaningful variable name and  using comments

**Comment by Sayad-Uddin-Tahsin** [comment]
> > > Please use meaningful variable names.
> > 
> > 
> > @nomandhoni-cs, sorry about that I guess I used meaningful names already but obviously it may be felt wrong on your perspective. Can you name the variables you didn't understand or need me to change?
> 
> Almost fine, not a major issue, This was just a request to use meaningful variable name and using comments

Roger that!
Lemme know if any issue arises! Also, lemme know for Dashboard modifications!

**Comment by nomandhoni-cs** [comment]
Have you tried to build the app with the latest changes you've made? 

If Yes, Is the App and Dashboard working flawlessly after installation? 

I tried, mine is giving some error after installation. But working fine in the terminal.

If your build version not working after installation, I've a possible fix.

**Comment by Sayad-Uddin-Tahsin** [comment]
> Have you tried to build the app with the latest changes you've made?
> 
> If Yes, Is the App and Dashboard working flawlessly after installation?
> 
> I tried, mine is giving some error after installation. But working fine in the terminal.
> 
> If your build version not working after installation, I've a possible fix.

@nomandhoni-cs, Sorry about that, a last-minute change on `resource_path` caused that issue mistakenly I'd removed a line which caused the application to fail

**Comment by Sayad-Uddin-Tahsin** [comment]
By the commit [2deab29](https://github.com/nomandhoni-cs/blink-eye/pull/40/commits/2deab29eb1f04f678b3b658249d92cba6a7f72cb), BlinkEye should work perfectly **STANDALONE**

**Pull request merged**
