### PR TITLE
(platform) added linux support

### LINKED ISSUE #16: Linux version.
Make a Linux executable for this program.

### PR DESCRIPTION
**Pull request by fluentmoheshwar**
This PR includes a script to build this application for Fedora Linux

Closes #16

### CODE REVIEW

**Comment by nomandhoni-cs** [comment]
@fluentmoheshwar, Have you tested the app made with this build in Linux? As I said I don't have a Linux machine, so that's why confirming from you.  Then we can release for the Linux

**Comment by fluentmoheshwar** [comment]
> @fluentmoheshwar, Have you tested the app made with this build in Linux? As I said I don't have a Linux machine now, so that's why confirming from you.  Then we can release for the Linux

I have tested the app on Fedora Workstation 39. It works fine there. But the user have to start the app manually from terminal. 
The app only works on fedora for now. Other distro support will be added soon. As I don't have access to them.

**Comment by nomandhoni-cs** [comment]
> > @fluentmoheshwar, Have you tested the app made with this build in Linux? As I said I don't have a Linux machine now, so that's why confirming from you.  Then we can release for the Linux
> 
> I have tested the app on Fedora Workstation 39. It works fine there. But the user have to start the app manually from terminal. The app only works on fedora for now. Other distro support will be added soon. As I don't have access to them.

Okay So Auto startup functionality is not implemented yet right?

**Comment by fluentmoheshwar** [comment]
> > > @fluentmoheshwar, Have you tested the app made with this build in Linux? As I said I don't have a Linux machine now, so that's why confirming from you.  Then we can release for the Linux
> > 
> > I have tested the app on Fedora Workstation 39. It works fine there. But the user have to start the app manually from terminal. The app only works on fedora for now. Other distro support will be added soon. As I don't have access to them.
> 
> Okay So Auto startup functionality is not implemented yet right? 

That's correct! However the user can add it to autostart manually.

**Comment by fluentmoheshwar** [comment]
> > > > > @fluentmoheshwar, Have you tested the app made with this build in Linux? As I said I don't have a Linux machine now, so that's why confirming from you.  Then we can release for the Linux
> > > > 
> > > > 
> > > > I have tested the app on Fedora Workstation 39. It works fine there. But the user have to start the app manually from terminal. The app only works on fedora for now. Other distro support will be added soon. As I don't have access to them.
> > > 
> > > 
> > > Okay So Auto startup functionality is not implemented yet right?
> > 
> > That's correct! However the user can add it to autostart manually.
> 
> @fluentmoheshwar  In windows I added that functionality from Inno Setup script.
> 
> Also One more thing, can you give me fresh build distributable file, so that I can put that in release, and download option for Linux in website

I'm working on it

**Comment by fluentmoheshwar** [comment]
> Also One more thing, can you give me fresh build distributable file, so that I can put that in release, and download option for Linux in website

@nomandhoni-cs here's the download link:
https://github.com/fluentmoheshwar/blink-eye/releases/download/v1.4.0/BlinkEye-1.4.0-1.fc39.x86_64.rpm

**Pull request merged**
