### PR TITLE
(chore) added desktop icon for linux and fixed some bugs

### PR DESCRIPTION
**Pull request by fluentmoheshwar**
This PR added desktop icon for linux and fixed some bugs in the build script

### CODE REVIEW

**Comment by fluentmoheshwar** [comment]
# DONT MERGE UNTIL I SAY IT'S STOPPED WORKING

**Comment by fluentmoheshwar** [comment]
It's fine now

**Comment by nomandhoni-cs** [comment]
> It's fine now

Should I merge now?

When work is in the progress you can use [WIP] at the start of the PR title, When all changes are done. You can remove [wip]

**Comment by fluentmoheshwar** [comment]
> > It's fine now
> 
> Should I merge now?
> 
> When work is in the progress you can use [WIP] at the start of the PR title, When all changes are done. You can remove [wip]

Thanks for the advice. Yes, you can merge it now.

**Pull request merged**
