### PR TITLE
(application) Added Mute-Unmute Feature for Windows in Break Screen

### PR DESCRIPTION
**Pull request by Sayad-Uddin-Tahsin**
* Added `sound-mute` & `sound-unmute` icon on `/application/Assets`
* Added both mute and unmute functionalities in one dynamic icon-based button [mentioned on [comment by @nomandhoni-cs](https://github.com/nomandhoni-cs/blink-eye/pull/37#issuecomment-2185075531)].
* Made the Blink Eye text and logo a bit smaller located in the top-right corner.

### CODE REVIEW

**Comment by Sayad-Uddin-Tahsin** [comment]
@nomandhoni-cs PR for Volume Unmute button mentioned [here](https://github.com/nomandhoni-cs/blink-eye/pull/34#issuecomment-2184949866)

**Review by fluentmoheshwar — APPROVED** [review]

**Comment by nomandhoni-cs** [comment]
@Sayad-Uddin-Tahsin  I really appreciate all the efforts you put in making the functionality to work flawlessly.

At the same time I can you focus little on the UI side of things

https://www.figma.com/design/oGN7DXX9x8pH5Mgt5FezNa/Blink-Eye-(Copy)?node-id=0-1&t=DUjkqt52eUzQx6bG-1

Here is the figma file where I brainstorm

- Mute Unmute feature wasn''t that important, So we're trying to show a little icon without text ( Additional: maybe swap the icon when mute and unmute)
- And In this file you can find exact color code of the intended theme. And Background was #000000 so it looks pure black in oled, IPS displays

## Main Focus is make the PopUp as much clean as possible, No unwanted things.


# Brainstorm 
### In Future Feature Bucket list
- Show the screen on  time
- I am wondering where is the best place to display the screen on time

**Comment by Sayad-Uddin-Tahsin** [comment]
@fluentmoheshwar What do you think about the logo on top-right corner?

**Comment by Sayad-Uddin-Tahsin** [comment]
> @Sayad-Uddin-Tahsin  I really appreciate all the efforts you put in making the functionality to work flawlessly.
> 
> At the same time I can you focus little on the UI side of things
> 
> https://www.figma.com/design/oGN7DXX9x8pH5Mgt5FezNa/Blink-Eye-(Copy)?node-id=0-1&t=DUjkqt52eUzQx6bG-1
> 
> Here is the figma file where I brainstorm
> 
> - Mute Unmute feature wasn''t that important, So we're trying to show a little icon without text ( Additional: maybe swap the icon when mute and unmute)
> - And In this file you can find exact color code of the intended theme. And Background was #000000 so it looks pure black in oled, IPS displays
> 
> - Help me brainstorm:  Also I was thinking what is the use case of the logo in the top right corner, Isn't it unnecessary? I am just figuring out what we could do to make the popup clutter free 
> 
> 
> ## Main Focus is make the PopUp as much clean as possible, No unwanted things.
> 
> 
> # Brainstorm 
> ### In Future Feature Bucket list
> - Show the screen on  time
> - I am wondering where is the best place to display the screen on time 

Also about the coloring, it's not `#000000`. Lemme clear the thing. As the current version of the UI has both Light and Dark theme (Synced with system theme), on CustomTkinter default configuration the colors are a bit off, like dark is a less dark and white is a bit less white. I believe there is a way to change the default (I think at least). What do you say? What to do?

**Comment by Sayad-Uddin-Tahsin** [comment]
@nomandhoni-cs Just a reminder, can you please tell me should I change the Break Screen Background color to `#000000` which will lead the `theme-based` background color to not work. Can you clarify your decision so that we can move on?

**Comment by Sayad-Uddin-Tahsin** [comment]
Commit [`a8fbf24`](https://github.com/nomandhoni-cs/blink-eye/pull/37/commits/a8fbf241f4b0ae149b85a01a7ba58e8c6d6ade8c):

- Added both mute and unmute functionalities in one dynamic `icon-based` button [mentioned on [comment by @nomandhoni-cs](https://github.com/nomandhoni-cs/blink-eye/pull/37#issuecomment-2185075531)].
- Made the `Blink Eye` text and `logo` a bit smaller located in the `top-right` corner.

**Comment by Sayad-Uddin-Tahsin** [comment]
Some Branch related things caused it to close unintentionally!

**Pull request merged**
